# Generated by Django 3.0.6 on 2020-05-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='summary_crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('url', models.URLField()),
                ('topic', models.CharField(max_length=10)),
                ('jeiba', models.TextField()),
                ('summary1', models.TextField()),
            ],
        ),
    ]
